services:
  setup:
    image: registry.apk-group.net/automation/modules/elasticsearch:${STACK_VERSION}
    container_name: es-setup
    user: "0"
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${KIBANA_PASSWORD} == x ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating node certs (es01 + kib01)";
          echo -ne \
          "instances:\n"\
          "  - name: es01\n"\
          "    dns:\n"\
          "      - es01\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: kib01\n"\
          "    dns:\n"\
          "      - kib01\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        echo "Setting file permissions"
        chown -R root:root config/certs;
        find . -type d -exec chmod 750 \{\} \;;
        find . -type f -exec chmod 640 \{\} \;;
        echo "Setup container finished - certs ready.";
      '

  elasticsearch:
    image: registry.apk-group.net/automation/modules/elasticsearch:${STACK_VERSION}
    container_name: es01
    depends_on:
      setup:
        condition: service_completed_successfully
    environment:
      - node.name=es01
      - cluster.name=smart-analyzer-es
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01/es01.key
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms${ES_JAVA_HEAP} -Xmx${ES_JAVA_HEAP}

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535

    volumes:
      - es-data:/usr/share/elasticsearch/data
      - certs:/usr/share/elasticsearch/config/certs

    ports:
      - "${ES_PORT}:9200"

    networks:
      - smart-analyzer-network

    healthcheck:
      test: ["CMD-SHELL", "curl -s --cacert /usr/share/elasticsearch/config/certs/ca/ca.crt -u elastic:${ELASTIC_PASSWORD} https://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: registry.apk-group.net/automation/modules/kibana:${STACK_VERSION}
    container_name: kib01
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certs/ca/ca.crt

      # Enable HTTPS on Kibana itself
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/kib01/kib01.crt
      - SERVER_SSL_KEY=/usr/share/kibana/config/certs/kib01/kib01.key
      - SERVER_PUBLICBASEURL=https://localhost:${KIBANA_PORT}

    volumes:
      - kibanadata:/usr/share/kibana/data
      - certs:/usr/share/kibana/config/certs

    ports:
      - "${KIBANA_PORT}:5601"

    networks:
      - smart-analyzer-network

networks:
  smart-analyzer-network:
    external: true

volumes:
  es-data:
  kibanadata:
  certs: